# ADDED for EZUA
#More information https://docs.ezmeral.hpe.com/unified-analytics/15/ManageClusters/importing-applications.html?hl=import
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "apptemplate.fullname" . }} # from helpers.tpl
  labels:
    {{- include "apptemplate.labels" . | nindent 4 }} # from helpers.tpl
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required "\nValid .Values.ezua.virtualService.endpoint is required !" }}
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "apptemplate.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local # from helpers.tpl
            port:
              number: {{ .Values.service.port }} # make sure this exists in value.yaml